### ISSUE TITLE
Issue with examples

### ISSUE THREAD

**Issue by mlabonne** [prometheus-eval/prometheus-eval#11]
Hi,

Thanks for this release and your paper. I noticed that there is an issue with the examples that are provided: `reference_answers` (plural) is the name of the argument instead of `reference_answer`. However, even with the correct name and a list, I wasn't able to get a feedback or a score.

**Comment by scottsuk0306** [comment]
Thank you for reporting this. I just fixed the issue you reported. Can you try again by downloading the new version (0.1.10) of our package, and use the updated example in our README.md?

**Comment by scottsuk0306** [comment]
Hi @mlabonne, Thank you for reporting this. I just fixed the issue you reported. Can you try again by downloading the new version (0.1.10) of our package, and use the updated example in our README.md?

**Comment by mlabonne** [comment]
Thanks it looks like it works now but it took 18 attempts to produce a feedback (it failed the first time). Is there something wrong with the way I use it (low seq length?)? https://colab.research.google.com/drive/1p3BlzQcRRX6ZWeGofyWf24LhJECPQCPc?usp=sharing

**Comment by scottsuk0306** [comment]
Yeah I think increasing max_model_len will solve the issue. We haven't tested prometheus model on max_model_len < 4096 tokens

**Comment by mlabonne** [comment]
Thanks for the clarification!
