### ISSUE TITLE
About the evaluation on direct assessment benchmarks

### ISSUE THREAD

**Issue by wangpf3** [prometheus-eval/prometheus-eval#16]
Hi authors,
Thanks for the great work! A few questions about the evaluation on the direct assessment benchmarks:
1. For MT-bench and FLASK, I saw that there are 3 "gpt4_score" and their corresponding feedbacks. I'm wondering how to calculate the scoring correlations against the scores. Do I need to sample 3 evaluations from the judge model and then compare them one by one?
2. Also for these datasets, I don't find the reference for each prompt. How do you conduct reference-based evaluation?

Would appreciate any clarification on these. Thank you!

**Comment by scottsuk0306** [comment]
Hi, @wangpf3! Thank you for the interest in our work! 

> 1. For MT-bench and FLASK, I saw that there are 3 "gpt4_score" and their corresponding feedbacks. I'm wondering how to calculate the scoring correlations against the scores. Do I need to sample 3 evaluations from the judge model and then compare them one by one?

Yes. For each instances, we first sampled 3 evaluations from the judge model and calculated the mean of three values. Then, we measured correlation with the mean of `gpt4_score`. 

> 2. Also for these datasets, I don't find the reference for each prompt. How do you conduct reference-based evaluation?

Actually, for these datasets, the `instruction` includes the reference answer. You can find the reference by searching `###Reference Answer (Score 5)`.

I hope this answers your question! Let me know if you need more clarifications.

**Comment by scottsuk0306** [comment]
For your information, we're also writing the documentation for running these evals. It will be updated in `eval/README.md` in few days.

**Comment by wangpf3** [comment]
Got it! Thank you Juyoung for the info!
