### ISSUE TITLE
[Question] Support for including context (RAG)?

### ISSUE THREAD

**Issue by austinmw** [prometheus-eval/prometheus-eval#22]
Hi, curious if there are any plans to support evaluating context along with question and reference answer?

**Comment by scottsuk0306** [comment]
Hi @austinmw ! I haven't thought about the idea you described, but I think it would be great if prometheus-eval supported this feature!

Just for reference, there were some approaches using Prometheus (version 1) for RAG evaluation. You can check it out here: [link](https://www.llamaindex.ai/blog/llamaindex-rag-evaluation-showdown-with-gpt-4-vs-open-source-prometheus-model-14cdca608277).

May I ask if you are interested in contributing to this feature? If yes, we can set up a new issue for feature implementation and discuss it further. 😊

**Comment by SeungoneKim** [comment]
@austinmw To add on to Juyoung's comments, I think it would be an interesting idea to add additional context to the {instruction}.

It's as if evaluating an LLM's response like it was in an open-book setting (while it could have been a closed-book setting actually).

We would be glad to discuss this in more detail if needed!
