### ISSUE TITLE
Question about multi-turn evaluation

### ISSUE THREAD

**Issue by jackyoung96** [prometheus-eval/prometheus-eval#24]
Hi, thank you for good work first.

Is there a template for multi-turn evaluation for relative comparison?

**Comment by scottsuk0306** [comment]
Hi @jackyoung96, thanks for your interest.

We don't have the template for multi-turn evaluation for relative comparison yet 😢 
Would you mind giving some kind of example responses (or multi-turn chat) that you want to evaluate?

**Comment by SeungoneKim** [comment]
Just to add on, you could add the whole interaction to {instruction}, this is how we evaluated on the MT-Bench for absolute grading & MT-Bench Human Judgment for relative grading!

**Comment by jackyoung96** [comment]
> Just to add on, you could add the whole interaction to {instruction}, this is how we evaluated on the MT-Bench for absolute grading & MT-Bench Human Judgment for relative grading!

Thank you for the answer!!
@scottsuk0306 I just asked a example such as the MT-bench, so @SeungoneKim 's answer is enough for me. Appreciate @SeungoneKim
