### ISSUE TITLE
Speed-up strategies

### ISSUE THREAD

**Issue by adhirajghosh** [prometheus-eval/prometheus-eval#25]
Hi, 
Thank you for your great work. I would like to look into ways in which I can improve the speed of feedback and score generation for pairwise ranking. Currently, generating scores for 3165 responses requires 3 GPU hours, using `"prometheus-eval/prometheus-7b-v2.0"` and `torch.float16`. While this is commendable, if there are ways to improve the speed of response generation, I would be happy to hear about and implement them.

**Comment by scottsuk0306** [comment]
Hi @adhirajghosh, I’m really excited to hear that you’re open to contributing! 😊

The time you described is actually way more longer than we expected though. When using `vllm`, it took us about 5 minutes on grading 1000 responses on 1 GPU (we tested on both A6000 and A100). I'm curious which code you're using for this.

**Comment by adhirajghosh** [comment]
Oh wow, that is a bit shocking. 
I too am using an [A100](https://developer.nvidia.com/blog/nvidia-ampere-architecture-in-depth/) GPU. The relevant code is taken and adapted from this repository's README:

#Loading the model
`judge = PrometheusEval(model_id="prometheus-eval/prometheus-7b-v2.0", relative_grade_template=PREFIX_PROMPT, dtype = torch.float16)`

#Specific instructions and rubrics (this one for image captioning)
`instruction_cap = "The ground truth captions of a provided image are listed here. They are separated by a semi-colon. Please carefully observe the image and come up with a caption for the image."
rubric_cap = "Is the answer well correlated with the ground truth captions?"`

# I retrieve ground truth and model responses separately. Code should still be readable.
`data = {
                        "instruction": instruction_cap,
                        "response_A": response1,
                        "response_B": response2,
                        "reference_answer": f"Ground truth captions: {ground_truth}",
                        "rubric": rubric_cap,
                    }`

`feedback, score = judge.single_relative_grade(**data)`

Any insight is greatly appreciated. Thank you for looking into this!

**Comment by scottsuk0306** [comment]
Thanks for sharing. I just added about [batch grading in our README](https://github.com/prometheus-eval/prometheus-eval?tab=readme-ov-file#batch-grading). Can you check this and change your implementation accordingly? Curious how much speed up you can get! 

Oh and also please set `dtype = 'bfloat16'` :)

**Comment by adhirajghosh** [comment]
This was extremely helpful. There is a bit of variation per batch with different numbers of retries but overall, I am close to the 1000 responses in 5 minutes statistic you initially provided.

Thanks again for your solution. If can help contribute to this work, please do let me know!

Cheers!
