### ISSUE TITLE
feature request: use model from HuggingFace Inference endpoint

### ISSUE THREAD

**Issue by jgrivolla** [prometheus-eval/prometheus-eval#26]
It would be very useful to be able to point to an external inference API endpoint (e.g. on HuggingFace), especially when the local computer running the experiment may not have the required resources to run the model.

This is e.g. possible with langchain with `HuggingFaceEndpoint` which can either point to the model id to download the weights, or to a URL to access the model remotely. A similar mechanism for prometheus-eval would be great.

**Comment by scottsuk0306** [comment]
Thanks for the suggestion @jgrivolla. We will definitely work on this before the end of May :)
