### ISSUE TITLE
Which directory is the relevant code for weight merging located in?

### ISSUE THREAD

**Issue by ychyhy** [prometheus-eval/prometheus-eval#34]
Hello, this work is great. But I can not find the relevant code for weight merging

**Comment by scottsuk0306** [comment]
Hi, @ychyhy! The instructions for merging is [here](https://github.com/prometheus-eval/prometheus-eval/tree/main/train/recipes/prometheus-v2.0) where we use [Lazy Mergekit notebook](https://colab.research.google.com/drive/1obulZ1ROXHjYLn6PPZJwRR6GzgQogxxb?usp=sharing) and [safetensors-merge-supermario](https://github.com/martyn/safetensors-merge-supermario). Let me know if you have further questions about it!
