### ISSUE TITLE
What are the rubricks for evaluation?

### ISSUE THREAD

**Issue by IsThatYou** [prometheus-eval/prometheus-eval#42]
It seems like the rubric can be important for getting the scores on the benchmarks shown in the paper. However, I can't find them anywhere in the repo or paper. It would be nice to know some of them :D

**Comment by scottsuk0306** [comment]
Hi @IsThatYou, you can refer to the predefined rubrics [here](https://github.com/prometheus-eval/prometheus-eval/blob/main/libs/prometheus-eval/prometheus_eval/prompts.py).

For replicating the scores specifically in the Prometheus 2 papers, we have [data loader](https://github.com/prometheus-eval/prometheus-eval/blob/main/eval/benchmark/data_loader.py) class for loading the relevant benchmark with scoring rubrics, but it is not documented yet.
