### ISSUE TITLE
Question about the using GPT4 to generate the reference answer

### ISSUE THREAD

**Issue by Xccanxin** [prometheus-eval/prometheus-eval#44]
Hi, i've read your papers and i've got a question about using GPT4 to generate the reference answers.
As you mentioned in PROMETHEUS1, an open-source, controlled version and inexpensive evaluation llm is needed.
However, training and testing this llm requires the using of GPT4 to generate the reference answer, otherwise it would lead to bad performance(table6 in PROMETHEUS1). 
It is confused to me why PROMETHEUS series could be effectively used. It seems contradictory to use an open-source, controlled version and inexpensive evaluation llm which is rely on GPT4 reference answers.  If we can apply GPT4 to generate reference answers, why don't we apply GPT4 to score the response?

**Comment by SeungoneKim** [comment]
@Xccanxin Hello, thanks for your great question!

I think it would be great to break down possible scenarios into two-folds.

First, there are cases/scenarios where a set of reference answers are already prepared for a fixed test set. This includes companies (where they have internal test sets) or academic benchmarks (like our recent benchmark called the BiGGen Bench: https://arxiv.org/abs/2406.05761 or many others). In this case, you could utilize them for better gradings.

Second, in scenarios where you don't have reference answers, as you mentioned, acquiring them with GPT-4 is one possible solution and we indeed conducted some of our experiments in this manner. 
- However, in our recent preprint, we also showed that even in reference-free evaluation settings, Prometheus 2 can function as a good judge compared to other base LMs with reference answers.
- In a practical sense, using GPT-4 to generated reference answers & evaluating with Prometheus 2 can halve the cost you would need to conduct reference-based evaluations.

Hope these answers your questions, and would be happy to discuss more if anything is not clear!

**Comment by Xccanxin** [comment]
thanks for your reply, it helps a lot!

**Comment by Xccanxin** [comment]
> @Xccanxin Hello, thanks for your great question!
> 
> I think it would be great to break down possible scenarios into two-folds.
> 
> First, there are cases/scenarios where a set of reference answers are already prepared for a fixed test set. This includes companies (where they have internal test sets) or academic benchmarks (like our recent benchmark called the BiGGen Bench: https://arxiv.org/abs/2406.05761 or many others). In this case, you could utilize them for better gradings.
> 
> Second, in scenarios where you don't have reference answers, as you mentioned, acquiring them with GPT-4 is one possible solution and we indeed conducted some of our experiments in this manner.
> 
> * However, in our recent preprint, we also showed that even in reference-free evaluation settings, Prometheus 2 can function as a good judge compared to other base LMs with reference answers.
> * In a practical sense, using GPT-4 to generated reference answers & evaluating with Prometheus 2 can halve the cost you would need to conduct reference-based evaluations.
> 
> Hope these answers your questions, and would be happy to discuss more if anything is not clear!

thanks for your reply, it helps a lot!
