### ISSUE TITLE
How to load "prometheus-8x7b-v2.0"

### ISSUE THREAD

**Issue by bittersweet1999** [prometheus-eval/prometheus-eval#52]
I have tried for gpu nums of 2,4,8 on A100 with below code
```
from prometheus_eval.vllm import VLLM
model_path = "prometheus-eval/prometheus-8x7b-v2.0"
model = VLLM(model=model_path, tensor_parallel_size=8)
```
but can not load model successfully, 
my environment are as belows:
```
python=3.10.14
vllm=0.5.1
torch=2.3.0
transformers=4.43.3
```
Could you provide your environment info if this MoE model can be loaded by vllm?

**Comment by scottsuk0306** [comment]
Hi @bittersweet1999, we used the following parameters throught the experiments (using 4 A100 gpus):

```python
from prometheus_eval.vllm import VLLM
model_path = "prometheus-eval/prometheus-8x7b-v2.0"
model = VLLM(model=model_path, max_model_len=8192, gpu_memory_utilization=0.9, tensor_parallel_size=4)
```

Let me know if you have further issues.

**Comment by bittersweet1999** [comment]
Thanks for your response, I use the code above to load the model, however the same error as below
![图片](https://github.com/user-attachments/assets/ec54f6e2-d467-42e8-8532-87eb772dc18e)
so I thinks this may caused by environment, can you provide me your version of vllm and transformers?

**Comment by bittersweet1999** [comment]
oh this should be a compile error, I will check my environment first, thank you
