### ISSUE TITLE
Finetune for structured output

### ISSUE THREAD

**Issue by shahules786** [prometheus-eval/prometheus-eval#56]
Most open-source libraries and projects using LLMs now prefer JSON-structured output to facilitate easier parsing and validation. This preference became a challenge when we tried to add support for Prometheus_eval models in [ragas](https://github.com/explodinggradients/ragas). Moving forward, we strongly recommend fine-tuning your models to produce JSON output to enhance usability in future versions.

**Comment by kuba2290** [comment]
I am currently struggling to parse JSON output from your model.

**Comment by SeungoneKim** [comment]
@shahules786 Thanks for the suggestion! 

Would you mind sharing what key-values you might need in the JSON-structured output? For instance, perhaps the "feedback" and "judgment"?

**Comment by shahules786** [comment]
@SeungoneKim In your case I think the keys would be score of type int and feedback of type string. It seems pretty straightforward. This could enable a lot more people to use these models with trust - parsing errors are always a problem while evaluating or in general building LLM software without type annotations and formating.
