### ISSUE TITLE
prometheus-eval lib is always returning score 5

### ISSUE THREAD

**Issue by rafaelliu** [prometheus-eval/prometheus-eval#58]
Prometheus model is scoring correctly between 1 and 5, but the lib is always returning score 5. The problem is the regex is matching the prompt template ([here for instance](https://github.com/prometheus-eval/prometheus-eval/blob/517c188222e5553fb14d799c3b5052cf2a441f57/libs/prometheus-eval/prometheus_eval/prompts.py#L18)), instead of Prometheus' generation.

Since Prometheus seems to reliably follow instruction to add score at the end of the response, I'd propose matching regex from end of string and longer term explore structured response.

**Comment by scottsuk0306** [comment]
@rafaelliu Thanks for catching this :) I also strongly agree about supporting structured responses to ensure robustness of llm-as-a-judge.
