### ISSUE TITLE
doc link not working for batch predictions

### ISSUE THREAD

**Issue by wise-east** [prometheus-eval/prometheus-eval#60]
This link in the README leads to a 404 error: https://prometheus-eval.github.io/prometheus-eval/docs/advanced-usage.html#53-handling-large-datasets

**Comment by scottsuk0306** [comment]
Hi @wise-east , thank you for bringing this to our attention! I've removed the link as the documentation is temporarily deprecated. For now, we're focusing on maintaining the README.md for usage instructions.
