### ISSUE TITLE
Plan to update eval benchmark documentation?

### ISSUE THREAD

**Issue by CharlieJCJ** [prometheus-eval/prometheus-eval#61]
Hi prometheus team! 

Thanks for the great work. Wondering when will the README in this section get updated?
https://github.com/prometheus-eval/prometheus-eval/tree/main/eval

Thanks.

**Comment by SeungoneKim** [comment]
Hey @CharlieJCJ, thanks for your interest! The section you referred to is for "meta-evaluation", which is evaluating evaluation models.

You could simply run
```
python3 run_evaluate.py --model_name "prometheus-eval/prometheus-8x7b-v2.0" --eval_data_names ["hhh_alignment_eval", "vicuna_eval", "flask_eval"]
```

If you're finding for just evaluating language models by using evaluator LMs, you could refer to the README page.

Let me know if this doesn't answer your questions!
