### ISSUE TITLE
Suggestion to remove reference answer from prompt if not provided

### ISSUE THREAD

**Issue by limshengxue** [prometheus-eval/prometheus-eval#64]
Hi, I kindly suggest to add a conditional statement to remove the whole section of "reference answer" from the prompt if it is not provided. Some models including gpt-4o were using the empty reference answer for its scoring.

**Comment by SeungoneKim** [comment]
Hello @limshengxue, thanks for your suggestion!

If you use the `ABSOLUTE_PROMPT_WO_REF` prompt (link below), you could avoid including a reference answer!

https://github.com/prometheus-eval/prometheus-eval/blob/b7a431a553b320e0a7cc49c6c5d3c54b1b840d39/libs/prometheus-eval/prometheus_eval/prompts.py#L27

**Comment by limshengxue** [comment]
Thanks!
